"title": "jkMap"
"menu.data": "Daten"
"menu.data.load": "Daten laden"
"menu.data.save": "Als Bild speichern"
"menu.data.save.dialog": "Bild speichern unter"
"menu.data.exit": "Programm beenden"
"menu.element.new": "Neues Element erstellen"
"menu.zoom": "Ansicht"
"menu.zoom.in": "Vergrößern"
"menu.zoom.out": "Verkleinern"
"menu.zoom.reset": "Zurück setzen"
"menu.control": "Bei Klick"
"menu.control.move": "Elemente bewegen"
"menu.control.edit": "Elemente bearbeiten"
"menu.control.info": "Element-Informationen anzeigen"
"menu.config": "Einstellung"
"menu.config.edit": "Ändern"

"info.title": "Element-Informationen"
"info.id": "Element-ID: "

"config.title": "Einstellungen"
"config.error.message": "Die Konfigurations-Einstellung ist nicht korrekt!"
"config.image.path": "Hintergrund-Bild"
"config.image.select": "Bild auswählen"
"config.image.fileChooser": "Bitte ein Bild-Datei auswählen"
"config.image.types": "Alle Bilder"

"config.dataSource.file": "Datenbank-Datei"
"config.dataSource.select": "Datenbank auswählen"
"config.dataSource.fileChooser": "Bitte ein Microsoft Access Datenbank auswählen"
"config.dataSource.types": "Alle Microsoft Access Datenbank"
"config.dataSource.table": "Tabellen-Name"
"config.image.factor": "1 m entspricht wieviel Pixeln?"
"config.image.width": "Breite des Bild-Dialoge (nicht des Bildes)"
"config.image.height": "Höhe des Bild-Dialoge (nicht des Bildes)"

"config.error.image": "Die angegebene Bild-Datei ist nicht vorhanden!"
"config.error.database": "Die angegebene Datenbank-Datei ist nicht vorhanden!"
"config.error.table": "Die angegebene Tabelle ist nicht in der Datenbank vorhanden!"
"config.error.factor": "Es ist nicht angegeben, wieviel Pixel auf dem Bild 1 m entsprechen!"
"config.error.width": "Die Breite des Bild-Dialogs ist nicht angegeben!"
"config.error.height": "Die Höhe des Bild-Dialogs ist nicht angegeben!"

"element.id": "ID"
"dialog.error" : "Fehler!"

"menu.element.rectangle": "Rechteck erstellen"
"element.rectangle.create": "Neues Rechteck erstellen"
"element.rectangle.edit": "Bestehendes Rechteck bearbeiten"
"element.rectangle.width": "Breite"
"element.rectangle.height": "Tiefe"
"element.rectangle.rotation": "Drehnung"
"error.rectangle.id" : "Die ID muss eine ganze Zahl sein"
"error.rectangle.width": "Die Breite muss eine Komma-Zahl sein"
"error.rectangle.height": "Die Tiefe muss eine Komma-Zahl sein"
"error.rectangle.rotation": "Die Rotation muss eine Komma-Zahl zwischen 0 und 360 sein"

"menu.element.circle": "Kreis erstellen"
"element.circle.create": "Neuen Kreis erstellen"
"element.circle.edit": "Bestehenden Kreis bearbeiten"
"element.circle.diameter": "Durchmesser"
"element.circle.rotation": "Drehnung"
"error.circle.id" : "Die ID muss eine ganze Zahl sein"
"error.circle.diameter": "Der Durchmesser muss eine Komma-Zahl sein"
"error.circle.rotation": "Die Rotation muss eine Komma-Zahl zwischen 0 und 360 sein"